### ISSUE TITLE
How can you hook into the quill events with quilljs-rails?

### ISSUE THREAD

**Issue by jfeust** [abhinavmathur/quilljs-rails#1]
https://quilljs.com/docs/api/#events

For example:
```
quill.on('text-change', function() {
  console.log('Text change!');
});
```

I would also need this to work for multiple quill editors on a single page.

**Comment by abhinavmathur** [comment]
According to the code in quill.global.js file :-

- It first scans for all the 'quill_container' classes.
-  Attaches Quill editors to those text fields/text-areas which has that class and assigns them an index starting from 0.
-  Each Quill instances can be accessed using the window object.

e.g. for the first Quill editor on the same page...you can access it with `window['quill-container-0']` and for the next one...it will be `window['quill-container-1']`

So in your case...to target the first quill editor starting from the top of the page, you can do something like:-
```
window['quill-container-0'].on('text-change', function() {
  console.log('Text change!');
});
```

**Comment by jfeust** [comment]
Perfect. Thank you.
