### ISSUE TITLE
How to customize the default settings?

### ISSUE THREAD

**Issue by wykhuh** [abhinavmathur/quilljs-rails#2]
Can you give more details about how to customize the default settings?

I'm installing quilljs-rails using the gem. I want to add the link and image to the toolbar. (I omitted the rest of toolbar code for this demo.)  I tried to set the defaults  `application.js`

```
//= require jquery
//= require quill.min
//= require quill.global
//= require turbolinks
//= require_tree .

  var defaults = {
    theme: 'snow',
    modules: {
        toolbar: [
          ['link', 'image']
        ]
    }
  };

  Quilljs.setDefaults(defaults)
```

`show.html.erb`
```
 <%= f.input :description, input_html: { class: 'quill_container' } %>
```

I end up with two editors for the description field.

<img width="646" alt="screen shot 2018-06-16 at 11 10 42 am" src="https://user-images.githubusercontent.com/6968611/41501259-fbabebb6-7155-11e8-9d5f-23f516b94ce0.png">

**Comment by abhinavmathur** [comment]
Interesting. Would like to know what Turbolinks version you are using. Also, does the problem happen when using it without Turbolinks?

**Comment by wykhuh** [comment]
turbolinks (5.1.0)
rails (5.0.7)

My app current is using Turbolinks.

If I remove Turbolinks, the quill editor does not load. I just get the normal text input.

**Comment by abhinavmathur** [comment]
@wykhuh I tried reproducing the error locally by using your app settings but seems like it is working fine(image below). Here is my application.js
```
//= require jquery.min.js
//= require quill.min
//= require quill.global
//= require turbolinks

//= require_tree .

  var defaults = {
    theme: 'snow',
    modules: {
        toolbar: [
          ['link', 'image']
        ]
    }
  };

  Quilljs.setDefaults(defaults)
```
In the CSS, I guess you are using the snow theme with bootstrap. 

For your convenience, I have added the latest version of Quill with this gem. You can use that version by using the following in your Gemfile and see whether that is working. For me, both the latest and the version specified in the gem are working.
```
gem 'quilljs-rails', github: 'abhinavmathur/quilljs-rails', branch: 'update_quilljs'
```

Not sure why removing Turbolinks is stopping Quill from working. Quill has no dependency on Turbolinks. From the screenshot, it seems like the page was initialized twice. Hope there is no duplicate code initializing Quill twice. 

![screenshot_quilljs](https://user-images.githubusercontent.com/2155942/41502335-9ca0cabc-7185-11e8-996b-afe94a1dc70a.png)

**Comment by wykhuh** [comment]
@abhinavmathur Found the issue. I was testing out two quills gem: one that required turbolinks and one did not.  I accidentally put the setup code  for your gem inside  `$(document).on('turbolinks:load', function() { .... }`.  Putting the setup code inside the function caused the editor to be rendered twice.  
 
Thanks for the help!
